namespace ResourcesManager {
  export const imgUrl: string = "http://pic28.photophoto.cn/20130818/0020033143720852_b.jpg"

  export const imgUrlTwo: string = "https://cdn.pixabay.com/photo/2019/08/08/11/33/stingray-4392776_960_720.jpg"

  export const videoUrl:string = "https://highlight-video.cdn.bcebos.com//video//6s//393e812e-b9e6-11eb-858e-7cd30ac11c56.mp4"

  export const webUrl: string = "https://www.mob.com"

  export const title: string = "测试分享消息标题"

  export const description: string = "测试分享消息描述"

  export const text: string = "测试分享消息内容"


}

export default ResourcesManager